### PR TITLE
Split monoid / semigroup instance for recent GHC

### PR DESCRIPTION
**Pull request by guibou**
For compatibility with newer base versions.

Note that I didn't try to keep backward compatibility with older version of base.

### CODE REVIEW

**Comment by NorfairKing** [comment]
Hi @guibou I haven't touched this repository in years. Would you like to have commit-rights and become a maintainer?

**Comment by guibou** [comment]
Actually, I just resurrected a toy project from 2017 which happened to have this lib as a dependency.

I won't promise that I'll take great care of the lib, but I'm fine with reviewing pull request and doing minor changes if needed.

**Comment by NorfairKing** [comment]
@guibou Don't worry, it's not much used.

**Comment by guibou** [comment]
@NorfairKing Should we do an hackage release?

**Comment by guibou** [comment]
:( It does not passes CI after merge, but I was not aware of the CI in the pull request.

I'll fix the CI.

**Pull request merged**
